/*
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.EmployeeBus;
import BUS.ImportBUS;
import DAO.CustomerDAO;
import DAO.EmployeeDAO;
import DAO.ImportDAO;
import DTO.CustomerDTO;
import DTO.EmployeeDTO;
import DTO.ImportDTO;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ImportGUI extends javax.swing.JPanel {

    private DefaultTableModel tableModel;

    public ImportGUI() {
        initComponents();
        initUI();
        setupTableSelectionListener();
    }

    /**
     * Creates new form ListEmployeePanel
     */
    private void initUI() {
        // Initialize table model
        if (import_table == null) {
            // Initialize table model with column names
            tableModel = new DefaultTableModel(new Object[]{"ID", "Product Name", "Manufacture Name", "Quantity", "Total Price",}, 0);
            import_table = new JTable(tableModel);
        } else {
            // Update the existing table model
            tableModel = (DefaultTableModel) import_table.getModel();
        }
        import_table.setEnabled(false);
        loadData("");
    }

    // Method to update the table model with ImportDTO data
    public void updateTable(List<ImportDTO> imports) {
        tableModel.setRowCount(0); // Clear existing data

        // Populate the table model
        for (ImportDTO importDTO : imports) {
            Object[] row = new Object[]{
                importDTO.getId(),
                importDTO.getProdname(), // Display product name instead of product ID
                importDTO.getManuName(),
                importDTO.getQuantity(),
                importDTO.getTotalPrice(), // Display manufacture name instead of manufacture ID
                importDTO.getTime(),
            };
            tableModel.addRow(row);
        }
    }

    private void loadData(String productName) {
        ImportDAO dao = new ImportDAO();
        List<ImportDTO> imports = dao.findImportsByProductName(productName);
        updateTable(imports);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        import_table = new javax.swing.JTable();
        import_btn = new javax.swing.JPanel();
        product_id = new javax.swing.JTextField();
        lastname_lb = new javax.swing.JLabel();
        manu_txt = new javax.swing.JTextField();
        product_lb = new javax.swing.JLabel();
        manu_lb = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        search_txt = new javax.swing.JTextField();
        searchlb = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        quantity_txt = new javax.swing.JTextField();
        quantity_lb = new javax.swing.JLabel();
        total_price_txt = new javax.swing.JTextField();
        total_price_lb = new javax.swing.JLabel();

        import_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ma", "Ten SP", "Nha SX", "SDT", "Tong Tien", "Thoi Gian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(import_table);

        product_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_idActionPerformed(evt);
            }
        });

        lastname_lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastname_lb.setText("Quan Ly Nhap Hang");

        manu_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manu_txtActionPerformed(evt);
            }
        });

        product_lb.setText("MaSP");

        manu_lb.setText("Ma NSX");

        create.setText("Nhap Hang");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        searchlb.setText("Search");

        search_btn.setText("Tim Kiem");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        quantity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_txtActionPerformed(evt);
            }
        });

        quantity_lb.setText("So Luong");

        total_price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_price_txtActionPerformed(evt);
            }
        });

        total_price_lb.setText("Tong Tien");

        javax.swing.GroupLayout import_btnLayout = new javax.swing.GroupLayout(import_btn);
        import_btn.setLayout(import_btnLayout);
        import_btnLayout.setHorizontalGroup(
            import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_btnLayout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(searchlb)
                .addGap(8, 8, 8)
                .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_btn)
                    .addGroup(import_btnLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total_price_lb)
                            .addComponent(manu_lb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manu_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(total_price_txt))))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(import_btnLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lastname_lb)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(import_btnLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(create)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(import_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(import_btnLayout.createSequentialGroup()
                        .addComponent(product_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(import_btnLayout.createSequentialGroup()
                        .addComponent(quantity_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        import_btnLayout.setVerticalGroup(
            import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastname_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manu_lb)
                    .addComponent(manu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_lb))
                .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(import_btnLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_price_lb)))
                    .addGroup(import_btnLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity_lb))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(create)
                .addGap(18, 18, 18)
                .addGroup(import_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchlb)
                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(import_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(import_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void product_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_idActionPerformed

    private void manu_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manu_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manu_txtActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        try {
            // Get input data from text fields
            int productId = Integer.parseInt(product_id.getText().trim());
            int quantity = Integer.parseInt(quantity_txt.getText().trim());
            double totalPrice = Double.parseDouble(total_price_txt.getText().trim());
            int manufactureId = Integer.parseInt(manu_txt.getText().trim());

            // Create an ImportDTO object with the input data
            ImportDTO importDTO = new ImportDTO(productId, quantity, totalPrice, manufactureId);

            // Call the createImportOrder method from ImportBUS to handle the import process
            ImportBUS importBUS = new ImportBUS();
            boolean importSuccess = importBUS.createImportOrder(importDTO);

            // Check if the import was successful
            if (importSuccess) {
                // If import was successful, display a success message or update the UI as needed
                JOptionPane.showMessageDialog(this, "Import successful", "Success", JOptionPane.INFORMATION_MESSAGE);

                // Optionally, you can update the table or any other UI components to reflect the changes
                loadData(""); // Update the import table
            } else {
                // If import failed, display an error message or handle the failure as needed
                JOptionPane.showMessageDialog(this, "Import failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // If there is a number format exception (e.g., invalid input), display an error message
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid numbers.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        String name = search_txt.getText().trim();
        loadData(name);
    }//GEN-LAST:event_search_btnActionPerformed

    private void quantity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_txtActionPerformed

    private void total_price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_price_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_price_txtActionPerformed

    private void setupTableSelectionListener() {
        import_table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) { // Prevent double events
                    displaySelectedEmployeeData();
                }
            }
        });
    }

    private void displaySelectedEmployeeData() {
        int selectedRow = import_table.getSelectedRow();
        if (selectedRow != -1) {
            int customerId = (Integer) import_table.getModel().getValueAt(selectedRow, 0);
            String name = (String) import_table.getModel().getValueAt(selectedRow, 1);
            String lastName = (String) import_table.getModel().getValueAt(selectedRow, 2);
            String phone = (String) import_table.getModel().getValueAt(selectedRow, 3);

            manu_txt.setText(name);
            product_id.setText(lastName);
            quantity_txt.setText(phone);
        } else {
            manu_txt.setText("");
            product_id.setText("");
            quantity_txt.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JPanel import_btn;
    private javax.swing.JTable import_table;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastname_lb;
    private javax.swing.JLabel manu_lb;
    private javax.swing.JTextField manu_txt;
    private javax.swing.JTextField product_id;
    private javax.swing.JLabel product_lb;
    private javax.swing.JLabel quantity_lb;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JLabel searchlb;
    private javax.swing.JLabel total_price_lb;
    private javax.swing.JTextField total_price_txt;
    // End of variables declaration//GEN-END:variables
}
